/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vidanec.edujp22.view;

import java.util.Arrays;
import vidanec.edujp22.utility.BrojZnakova;





/**
 *
 * @author Ivan
 */
public class LjubavniKalkulator extends javax.swing.JFrame {

    /**
     * Creates new form LjubavniKalkulator
     */
    public LjubavniKalkulator() {
        initComponents();
        setTitle("Ljubavni Kalkulator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtImePrvo = new javax.swing.JTextField();
        txtImeDrugo = new javax.swing.JTextField();
        lblUpute = new javax.swing.JLabel();
        lblIspisImena = new javax.swing.JLabel();
        lblSlova = new javax.swing.JLabel();
        btnGumb = new javax.swing.JButton();
        lblPostotak = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUpute.setText("Upisite dva imena:");

        lblIspisImena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIspisImena.setText("Imena");

        lblSlova.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSlova.setText("Slova");

        btnGumb.setText("Enter");
        btnGumb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGumbActionPerformed(evt);
            }
        });

        lblPostotak.setText("Postotak");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(btnGumb))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSlova)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(354, 354, 354)
                            .addComponent(lblIspisImena))
                        .addComponent(lblPostotak))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(lblUpute)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(txtImePrvo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(txtImeDrugo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblUpute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImePrvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImeDrugo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnGumb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblIspisImena)))
                .addGap(29, 29, 29)
                .addComponent(lblSlova)
                .addGap(31, 31, 31)
                .addComponent(lblPostotak)
                .addContainerGap(331, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGumbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGumbActionPerformed
        // TODO add your handling code here:
        String prvoIme = txtImePrvo.getText().toUpperCase();
        String drugoIme = txtImeDrugo.getText().toUpperCase();
        String obaImena = prvoIme+drugoIme;
        lblIspisImena.setText(prvoIme+" "+drugoIme);
        
        
        
        char[] charArray = obaImena.toCharArray();
        Arrays.sort(charArray);
        String sortedString = new String(charArray);
        lblSlova.setText(sortedString);
             
        //postotak
        if(txtImePrvo.getText().matches("[a-zA-Z]+") && txtImeDrugo.getText().matches("[a-zA-Z]+")) {
       lblPostotak.setText(BrojZnakova.countChars(txtImePrvo.getText(), txtImeDrugo.getText())+ "% se vole");
        } else {
            lblPostotak.setText("Dozvoljena samo slova");
        }
    }//GEN-LAST:event_btnGumbActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGumb;
    private javax.swing.JLabel lblIspisImena;
    private javax.swing.JLabel lblPostotak;
    private javax.swing.JLabel lblSlova;
    private javax.swing.JLabel lblUpute;
    private javax.swing.JTextField txtImeDrugo;
    private javax.swing.JTextField txtImePrvo;
    // End of variables declaration//GEN-END:variables



}


